language: node_js
node_js:
- node
cache: npm
deploy:
  provider: heroku
  api_key:
    secure: m+GwR64rggggavbiXb4ZlVE/PkFyKr2OEdwNTOwAew+poB4gVSr5Q1iEyK8Qo1Xqzw/pohY54fn4DqC15FfIaFYhk6A2o1hpgnYUXagILusbYxIcLGm6EPAeV65y9y88whrfrAW0dfjoJjgWmZ59OE1dA3Fdn2X/TZeuhEXXAAvtLAziqhcde/SBm8ZlN7BizCeIw0AVmqAWrLLWHDk5eBtSzIwuTRIss3zV2FYu4py6OpSOybe422nD+E7GictAMkFfO/AxPoGsQ6mGYuXRJovN/G5QWVM8UoPthblvy2MDLWzQP4JUFsWwRleruBlDjHqPvA/olJpEO+4oFqbPkpzGVcIlu/aNeucTYjesCk40KTWEI+pHyNBWSjz4N4egGgs/W7o6wNzU38ENnfvyTSSuYgv1CYgK12cnHBEv5ibNWWU5H5nLEQiQ8RdGsxXjBdepFBUf0D9xjHd0iC3SOPl6stlhQSX08I2innq0gbepFQaRROVwk/hDC0xuh5T0Gn8dx4SxRtk89R+AxVnWtoWa3Y4+xBQwCNkuEC8NnWYutpX929hOGAN3Mui2gFYM1c70zcQOQRm+2WCTGk2GIh47ljmk6xz8nCVrqw8nO3qbAQq6tGTXzDOTPaKsWM3qEzCqCW+3Qlo1dHd56z6DMuhdwaw2DLpImT1Wg2dknaI=
  app: septa-view-api
services:
- mongodb
